// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/VizzleTF/external-dns-openwrt-webhook/pkg/openwrt (interfaces: OpenWRT)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/openwrt/openwrt.go -package=mocks github.com/VizzleTF/external-dns-openwrt-webhook/pkg/openwrt OpenWRT
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	openwrt "github.com/VizzleTF/external-dns-openwrt-webhook/pkg/openwrt"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenWRT is a mock of OpenWRT interface.
type MockOpenWRT struct {
	ctrl     *gomock.Controller
	recorder *MockOpenWRTMockRecorder
	isgomock struct{}
}

// MockOpenWRTMockRecorder is the mock recorder for MockOpenWRT.
type MockOpenWRTMockRecorder struct {
	mock *MockOpenWRT
}

// NewMockOpenWRT creates a new mock instance.
func NewMockOpenWRT(ctrl *gomock.Controller) *MockOpenWRT {
	mock := &MockOpenWRT{ctrl: ctrl}
	mock.recorder = &MockOpenWRTMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenWRT) EXPECT() *MockOpenWRTMockRecorder {
	return m.recorder
}

// ApplyDNSRecords mocks base method.
func (m *MockOpenWRT) ApplyDNSRecords(ctx context.Context, remove, add []openwrt.DNSRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDNSRecords", ctx, remove, add)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDNSRecords indicates an expected call of ApplyDNSRecords.
func (mr *MockOpenWRTMockRecorder) ApplyDNSRecords(ctx, remove, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDNSRecords", reflect.TypeOf((*MockOpenWRT)(nil).ApplyDNSRecords), ctx, remove, add)
}

// GetDNSRecords mocks base method.
func (m *MockOpenWRT) GetDNSRecords(arg0 context.Context) (map[string]openwrt.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSRecords", arg0)
	ret0, _ := ret[0].(map[string]openwrt.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSRecords indicates an expected call of GetDNSRecords.
func (mr *MockOpenWRTMockRecorder) GetDNSRecords(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSRecords", reflect.TypeOf((*MockOpenWRT)(nil).GetDNSRecords), arg0)
}
